# Generated by Django 5.2.14 on 2026-05-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminpanel_remove_contact_phone_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpanel',
            options={'verbose_name': 'Byudjet', 'verbose_name_plural': 'Byudjetlar'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name="Bog'lanildi"),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('sold_out', 'Tugagan'), ('upcoming', 'Kutilmoqda')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Byudjet ($)'),
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.project', verbose_name='Loyiha'),
        ),
        migrations.AlterField(
            model_name='project',
            name='available_numbers',
            field=models.IntegerField(verbose_name="Bo'sh xonalar"),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floor',
            field=models.IntegerField(verbose_name='Qavatlar soni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx ($)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rooms',
            field=models.IntegerField(verbose_name='Xonalar soni'),
        ),
    ]
